# Generated by Django 4.1.2 on 2022-10-31 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_booking_group_size_alter_booking_approved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='TableReservation',
        ),
    ]
