# Generated by Django 4.1.2 on 2022-10-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_booking_tablereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='full_name',
            field=models.CharField(default='junaid', max_length=255),
            preserve_default=False,
        ),
    ]
