# Generated by Django 4.1.2 on 2022-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tablereservation_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(default='junaid@gmail.com', max_length=355),
            preserve_default=False,
        ),
    ]
