# Generated by Django 4.1.2 on 2022-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tablereservation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('recipe_name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
            ],
        ),
    ]
