# Generated by Django 4.1.2 on 2022-11-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.menucategory'),
            preserve_default=False,
        ),
    ]
